// realisation/react-project/src/Components/Input.jsx
export default function Input(props) {
    const inputEl = props.element === "input" ? (
        <input
            type={props.type}
            name={props.name}
            value={props.value}
            id={props.id}
            placeholder={props.placeholder}
            onChange={props.handleChange}
        />
    ): (
        <textarea name={props.name} value={props.value} onChange={props.handleChange}></textarea>
    );
    return (
        <label htmlFor={props.id}>
            <span>{props.label}</span>
            {inputEl}
        </label>
    )
}

// realisation/svelte-project/src/lib/Input.svelte
<script>
    export let element = "input";
    export let label = "";
    export let type = "text";
    export let name = "";
    export let placeholder = "";
    export let value = "";
    export let width = "";
    let inp_class = "w-full h-10 rounded-md border-2 border-gray-300 p-1";

    const handleInput = (e) => {
        value = e.target.value;
    };
</script>

<label class="{width} flex flex-col justify-between items-start mt-3">
    <span class="w-full">{label}</span>
    {#if element == "textarea"}
        <textarea class={inp_class} {name} {value} {placeholder} on:input={handleInput}></textarea>
    {:else}
        <input class={inp_class} {type} {name} {value} {placeholder} on:input={handleInput} />
    {/if}
</label>
